export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const WRONG_CREDENTIAL = 'WRONG_CREDENTIAL';
export const ADD_BOOK_DATA_RESPONSE = 'ADD_BOOK_DATA_RESPONSE';
export const RESET_BOOK_DATA = 'RESET_BOOK_DATA';
export const EDIT_BOOK = 'EDIT_BOOK';
export const FETCH_ALL_BOOK ='FETCH_ALL_BOOK';
export const FETCH_ALL_USER ='FETCH_ALL_USER'